// Define columns to remove
export const columnsToRemove = [
  1, 2, 4, 5, 7, 9, 12, 13, 14, 15, 16, 18, 19, 20, 21, 24, 25, 26, 27, 30, 31,
  32, 33, 34, 35, 37, 38, 39, 40,
];

// Define rows to remove
export const initialRowsToRemove = [0, 1, 2, 3, 4];

// Define words to be removed "Infracció", "il·licit", "Pèrdua", "Diversos", "Maltractament", "joc"
export const wordsToRemove = [
  "1/70",
  "1/2001",
  "10/19",
  "64/95",
  "Aband",
  "Accident",
  "Activitat",
  "administratives",
  "Aldarulls",
  "autèntic",
  "autorit",
  "circulació",
  "Comunicació",
  "Cond",
  "Consum",
  "convivència",
  "Contra",
  "d'expulsió",
  "Deixar",
  "deslluïments",
  "Deso",
  "dipositant",
  "Diversos",
  "Documental",
  "Dret",
  "Eo-",
  "Es-",
  "Escalada",
  "estranger",
  "Exped",
  "Extradició",
  "Frustració",
  "familiar",
  "fluïd",
  "flora",
  "fortuïts",
  "Fugit",
  "Identi",
  "il·licit",
  "Impagament",
  "imprescindible",
  "imprudència",
  "Incompl",
  "industrial",
  "Infracció",
  "infraccions",
  "Ingrés",
  "Intervenció",
  "Introduir",
  "irregularitats",
  "joc",
  "Localització",
  "Llançament",
  "Llei",
  "Maltractament",
  "Manca",
  "Manquen",
  "manera",
  "Negativa",
  "Negligència",
  "Obstaculització",
  "Obstrucció",
  "Ocupació",
  "Omissió",
  "Ordre",
  "Pèrdua",
  "Permanència",
  "Pertorbació",
  "Protecció",
  "Ps-realitz",
  "Quebrantar",
  "Recuperació",
  "règim",
  "regulació",
  "Remoció",
  "residus",
  "respecte",
  "reunio",
  "Seguretat",
  "suïcidi",
  "Supressió",
  "Tinença",
  "tòxi",
  "trànsit",
  "Trencament",
  "Trobada",
  "Velocitat",
];
