// Define columns to remove
export const columnsToRemove = [
  1, 2, 4, 5, 7, 9, 12, 13, 14, 15, 16, 18, 19, 20, 21, 24, 25, 26, 27, 30, 31,
  32, 33, 34, 35, 37, 38, 39, 40,
];

// Define rows to remove
export const initialRowsToRemove = [0, 1, 2, 3, 4];

// Define words to be removed "Infracció", "il·licit", "Pèrdua", "Diversos", "Maltractament", "joc"
export const wordsToRemove = [
  "Abandonament",
  "Accident",
  "Activitat",
  "administratives",
  "Aldarulls",
  "autoritat",
  "circulació",
  "Cond",
  "Consum",
  "convivència",
  "Contra",
  "d'expulsió",
  "deslluïments",
  "Desobediència",
  "Diversos",
  "estranger",
  "estrangeria",
  "familiar",
  "flora",
  "Fugit",
  "Identificació",
  "il·licit",
  "imprudència",
  "industrial",
  "Infracció",
  "infraccions",
  "Ingrés",
  "Intervenció",
  "irregularitats",
  "joc",
  "Localització",
  "Maltractament",
  "Negativa",
  "Ocupació",
  "Pèrdua",
  "Permanència",
  "Protecció",
  "Recuperació",
  "regulació",
  "residus",
  "respecte",
  "reunio",
  "suïcidi",
  "Supressió",
  "Tinença",
  "trànsit",
  "Trencament",
  "Trobada",
];
